overrides:
  agentic-deckgl: link:../../../../../../../.local/share/pnpm/global/5/node_modules/@carto/agentic-deckgl
  '@carto/agentic-deckgl': link:../../../../../ps-frontend-tools-poc/agentic-deckgl
